version: '3'
# Other docker-compose examples in /examples
##tst
services:
  minecraft:
    build: .
    ports:
      - "25565:25565"
    volumes:
      - "mc:/data"
    environment:
      EULA: "TRUE"
    restart: always
volumes:
  mc:
